### ISSUE TITLE
ValueError: could not broadcast input array while running the code from UnitMatchPy Demo Notebook

### ISSUE THREAD

**Issue by MingChingChiang** [EnnyvanBeest/UnitMatch#94]
Hi,
My name is Ming-Ching Chiang from OIST, Japan.

First of all, thank you for developing such useful tools.
I'm trying to run the UnitMatchPy since I'm using OpenEphys GUI for my Neuropixels recording.
I have used spikeinterface to wrap my recordings and calling kilosort4 for spikesorting.
After the sorting I used Bombcells to create quality matrices.
I follow the same analysis procedure for all of my dataset.
However, when I try to generate the RawWaveforms folder for UnitMatch, I got the following error messages:

[Parallel(n_jobs=-1)]: Using backend LokyBackend with 28 concurrent workers.
[Parallel(n_jobs=-1)]: Done   5 tasks      | elapsed:    2.4s
[Parallel(n_jobs=-1)]: Done  16 tasks      | elapsed:    2.5s
[Parallel(n_jobs=-1)]: Done  29 tasks      | elapsed:    3.8s
[Parallel(n_jobs=-1)]: Done  42 tasks      | elapsed:    4.7s
[Parallel(n_jobs=-1)]: Done  57 tasks      | elapsed:    4.7s
---------------------------------------------------------------------------
_RemoteTraceback                          Traceback (most recent call last)
_RemoteTraceback: 
"""
Traceback (most recent call last):
  File "c:\Users\MING-CHIANG\AppData\Local\anaconda3\envs\si_env\Lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
        ^^^^^^^^^^^
  File "c:\Users\MING-CHIANG\AppData\Local\anaconda3\envs\si_env\Lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\MING-CHIANG\AppData\Local\anaconda3\envs\si_env\Lib\site-packages\joblib\parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\MING-CHIANG\AppData\Local\anaconda3\envs\si_env\Lib\site-packages\joblib\parallel.py", line 598, in <listcomp>
    return [func(*args, **kwargs)
            ^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\MING-CHIANG\AppData\Local\anaconda3\envs\si_env\Lib\site-packages\UnitMatchPy\extract_raw_data.py", line 162, in extract_a_unit_KS4
    all_sample_waveforms[i] = tmp
    ~~~~~~~~~~~~~~~~~~~~^^^
ValueError: could not broadcast input array from shape (54,384) into shape (61,384)
"""

The above exception was the direct cause of the following exception:
...
--> [763](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/joblib/parallel.py:763)         raise self._result
    [764](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/joblib/parallel.py:764)     return self._result
    [765](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/joblib/parallel.py:765) finally:

ValueError: could not broadcast input array from shape (54,384) into shape (61,384)

Moreover, sometimes I can successfully execute the code to **#Extract the units to generate RawWaveforms folder**

I'm wondering is there anything I can do to solve this problem?
Can I just inactivate the parallel?

Another follow up question is that some of my units have different labels from kilosort and bombcell, 

Can I force the **util.load_good_waveforms** to select goodunits labels from kilosort but not from bombcell's tsv? 
The reason I ask this question is because in your erd.extract_KS_data you select good_units based from kilosort's **cluster_group.tsv**, 
but in your  util.load_good_waveforms you select good_units based on **cluster_bc_unitType.tsv**, which overwrite the good_units from kilosort labeling and then cause another error. 

Thank you very much for reading my post.
Please let me know if you need more parameters or information for my analysis procedure.

Best,
Ming-Ching

**Comment by Sam-Dodgson** [comment]
Hi this is Sam I will try to answer your questions in order:

1. I have just pushed a change to the work in progress branch which should fix the error you had about extracting raw waveforms. To explain what the problem was, in unitmatch for each unit we extract spikes, which is about ~80/60 samples . So we cannot chose spikes too close to the start or the end of the recording as their isnt a full spike. With KS4 they changed how they recorded some information so they take ~20 samples before the spike and ~40 after, before the code was ignoring an area of 30 samples either side, this led to your error if the final spike for a unit is between 30 and 40 samples away from the recording! I have fixed this in the demo notebooks so it blocks 40 samples either side.
2. The line of code `wave_paths, unit_label_paths, channel_pos = util.paths_from_KS(KS_dirs)` will try to automatically find all the files needed for UnitMatch, which by default will try to get a bombcell file (We recommend bombcell or manual curation!) however if you want to change any of these file you can do so after that line of code e.g `unit_label_paths[0] = 'new/path` would change the first session unit labels to whatever path you provided.

Let me know if this solves everything or if you have any other questions.

**Comment by MingChingChiang** [comment]
Hi Sam, 
Thank you for the explination and the new push of the example codes.
I can successfully save the RawWaveform for my sessions. 
However, when I try to extract parameters from waveform, I encounter a new error

extracted_wave_properties = ov.extract_parameters(waveform, channel_pos, clus_info, param)

---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
Cell In[62], [line 3](vscode-notebook-cell:?execution_count=62&line=3)
      [1](vscode-notebook-cell:?execution_count=62&line=1) # Step 1
      [2](vscode-notebook-cell:?execution_count=62&line=2) #Extract parameters from waveform
----> [3](vscode-notebook-cell:?execution_count=62&line=3) extracted_wave_properties = ov.extract_parameters(waveform, channel_pos, clus_info, param)

File c:\Users\MING-CHIANG\AppData\Local\anaconda3\envs\si_env\Lib\site-packages\UnitMatchPy\overlord.py:29, in extract_parameters(waveform, channel_pos, clus_info, param)
     [25](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/overlord.py:25) waveform = pf.detrend_waveform(waveform)
     [27](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/overlord.py:27) max_site, good_idx, good_pos, max_site_mean = pf.get_max_sites(waveform, channel_pos, clus_info, param)
---> [29](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/overlord.py:29) spatial_decay_fit , spatial_decay,  d_10, avg_centroid, avg_waveform, peak_time = pf.decay_and_average_waveform(waveform, channel_pos, good_idx, max_site, max_site_mean, clus_info, param)
     [31](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/overlord.py:31) amplitude, waveform, avg_waveform = pf.get_amplitude_shift_waveform(waveform, avg_waveform, peak_time, param)
     [33](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/overlord.py:33) waveform_duration, avg_waveform_per_tp, good_wave_idxs = pf.get_avg_waveform_per_tp(waveform,channel_pos, d_10, max_site_mean, amplitude, avg_waveform, clus_info, param)

File c:\Users\MING-CHIANG\AppData\Local\anaconda3\envs\si_env\Lib\site-packages\UnitMatchPy\param_functions.py:238, in decay_and_average_waveform(waveform, channel_pos, good_idx, max_site, max_site_mean, clus_info, param)
    [236](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/param_functions.py:236) dist_to_max_proj = np.linalg.norm(loc - avg_centroid[:,i,cv].T, axis = 1) #it is transposed here
    [237](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/param_functions.py:237) weight = (d_10[i,cv] - dist_to_max_proj) / d_10[i,cv]
--> [238](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/param_functions.py:238) avg_waveform[:,i,cv] = np.nansum( waveform[i,:,tmp_idx.astype(bool),cv].T * np.tile(weight, (spike_width, 1)), axis = 1 ) / np.sum(weight)
    [240](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/param_functions.py:240) #significant time points 
    [241](file:///C:/Users/MING-CHIANG/AppData/Local/anaconda3/envs/si_env/Lib/site-packages/UnitMatchPy/param_functions.py:241) wave_duration_tmp = np.argwhere( np.abs(avg_waveform[:,i,cv]) - np.mean(avg_waveform[0:20,i,cv]) > 2.5 * np.std(avg_waveform[0:20,i,cv], axis = 0))

ValueError: operands could not be broadcast together with shapes (61,30) (82,30)

My assumption for this error is due to the new parameter max_width, but I'm not sure how to fix this problem from the source code.
But I will try to play with the source codes a bit.

Thank you very much for your help!
Best regards,
Ming-Ching

**Comment by Sam-Dodgson** [comment]
Hi, with the shapes being (61,30) and (82,30) i think you have made the total waveform width (spike_width) different for some sessions? 
This would likely lead to the error above.
best,
sam

**Comment by MingChingChiang** [comment]
Thanks for the reply, I found the source of my error happens  while I get default parameters 
param = default_params.get_default_param()
The spike_width in the default setting is 82 where the spike_width for kilosort4 sorted units is 61.
After I add the following evaluation I fixed the error I had.
if KS4_data == True:
   param['spike_width'] = 61

**Comment by Andrianarivelo** [comment]
Hello, 

I had exatcly the same issue when trying to extract waveform from KS4 data, 
I used the following parameters : # Set Up Parameters
sample_amount = 500  # for both CV, at least 500 per CV
spike_width = 61  # assuming 30khz sampling, 82 and 61 are common choices, covers the AP and space around needed for processing
half_width = np.floor(spike_width / 2).astype(int)
max_width = np.floor(spike_width / 2).astype(
    int)  # Size of area at start and end of recording to ignore to get only full spikes
n_channels = 384  # neuropixels default
extract_good_units_only = False  # bool, set to true if you want to only extract units marked as good

KS4_data = True  # bool, set to true if using Kilosort, as KS4 spike times refer to start of waveform not peak
if KS4_data:
    samples_before = 20
    samples_after = spike_width - samples_before

 I tried different values of spike width (from 10 to 82) and reduced sample before but nothing fixed the issue...

```
[Parallel(n_jobs=-1)]: Using backend LokyBackend with 32 concurrent workers.
[Parallel(n_jobs=-1)]: Done   8 tasks      | elapsed:    3.9s
[Parallel(n_jobs=-1)]: Done  21 tasks      | elapsed:    4.3s
[Parallel(n_jobs=-1)]: Done  34 tasks      | elapsed:    5.0s
joblib.externals.loky.process_executor._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\externals\loky\process_executor.py", line 463, in _process_worker
    r = call_item()
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\externals\loky\process_executor.py", line 291, in __call__
    return self.fn(*self.args, **self.kwargs)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\parallel.py", line 598, in __call__
    return [func(*args, **kwargs)
            ~~~~^^^^^^^^^^^^^^^^^
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\UnitMatchPy\extract_raw_data.py", line 163, in extract_a_unit_KS4
    all_sample_waveforms[i] = tmp
    ~~~~~~~~~~~~~~~~~~~~^^^
ValueError: could not broadcast input array from shape (60,384) into shape (61,384)
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "D:\NPX\UnitMatch_prepare_data.py", line 110, in <module>
    avg_waveforms = Parallel(n_jobs=-1, verbose=10, mmap_mode='r', max_nbytes=None)(
        delayed(erd.extract_a_unit_KS4)(sample_idx[uid], data, samples_before, samples_after, spike_width,
                                        n_channels, sample_amount) for uid in range(n_units))
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\parallel.py", line 2007, in __call__
    return output if self.return_generator else list(output)
                                                ~~~~^^^^^^^^
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\parallel.py", line 1650, in _get_outputs
    yield from self._retrieve()
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\parallel.py", line 1754, in _retrieve
    self._raise_error_fast()
    ~~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\parallel.py", line 1789, in _raise_error_fast
    error_job.get_result(self.timeout)
    ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\parallel.py", line 745, in get_result
    return self._return_or_raise()
           ~~~~~~~~~~~~~~~~~~~~~^^
  File "C:\Users\bellone\.conda\envs\UnitMatch\Lib\site-packages\joblib\parallel.py", line 763, in _return_or_raise
    raise self._result
ValueError: could not broadcast input array from shape (60,384) into shape (61,384)

Process finished with exit code 1
```
Thanks for the help
